### ISSUE TITLE
just one question about streaming

### ISSUE THREAD

**Issue by tierline1** [ErAz7/Ninja#4]
Hello! ninja & jonin works fine!

But i wonder is it possible to configure this app that prevent file.mkv size growing?
while streaming audio and video, the stream is written to a file and it grows in size, but I do not need the entire recording.
maybe some file rotate and when siaze exeeds N mb rewrite it?

or mabe possible to set video and audio quality to reduce file size?

**Comment by ErAz7** [comment]
currently it doesn't support this behavior since it's not supposed to stream very large size of data using `shell stream` feature

**Comment by ErAz7** [comment]
but for video/audio quality, it depends on what you use to record. I believe FFmpeg should have options for that purpose
